baseurl = "https://denishaine.ca/"
languageCode = "en-us"
title = "Denis Haine"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
enableEmoji = true
footnotereturnlinkcontents = "↩"
rssLimit = 30

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "Publications"
    url = "/publication/"
[[menu.main]]
    name = "Software"
    url = "/software/"
[[menu.main]]
    name = "Blog"
    url = "/blog/"

[params]
    description = "Personal website of Denis Haine."
    dateFormat = "2006-01-02"
    customCSS = ["css/custom.css"]
    customJS = ["js/center-img.js", "js/right-quote.js", "js/no-highlight.js", "js/fix-footnote.js"]
    
    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml", "tex"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

    [params.social]
    twitter = "denishaine"
    github = "dhaine"
    linkedin = "in/denishaine"
    stackoverflow = "users/8126916/denis"
    orcid = "0000-0002-6691-7335"
    researchgate = "profile/Denis_Haine"