---
title: Episensr 0.9.0 now available on CRAN
author: Denis Haine
date: '2017-08-21'
slug: episensr-090-rmd
categories: ['R']
tags: ["episensr", "rstats"]
---



<p>A small update for my <a href="https://cran.r-project.org/package=episensr%20%22episensr%22"><code>episensr</code></a> R package is now available on CRAN.
The update focus on misclassification.</p>
<p>First, covariate misclassification is now available, via the function
<code>misclassification_cov</code>.
For example, the paper by <a href="http://www.bmj.com/content/330/7495/815">Berry et
al.</a> looked if misclassification of the
confounding variable <em>in vitro fertilization</em> (IVF), a confounder, resulted
wrongly on an association between increase folic acid and having twins.
IVF increases the risk of twins, and women undergoing IVF might be more likely
to take folic acid supplements, i.e. IVF would be a confounder between vitamins
and twins.
Data on IVF were not available and a proxy for it was used, <em>period of
involuntary childlessness</em>.
However, it was a poor proxy for IVF, with a sensitivity of 60% and a
specificity of 95%.
These bias parameters were assumed to be nondifferential.
Here’s the code with <code>episensr</code>:</p>
<pre class="r"><code>library(episensr)</code></pre>
<pre><code>## Registered S3 methods overwritten by &#39;ggplot2&#39;:
##   method         from 
##   [.quosures     rlang
##   c.quosures     rlang
##   print.quosures rlang</code></pre>
<pre class="r"><code>misclassification_cov(array(c(1319, 38054, 5641, 405546, 565, 3583,
                              781, 21958, 754, 34471, 4860, 383588),
                            dimnames = list(c(&quot;Twins+&quot;, &quot;Twins-&quot;),
                                            c(&quot;Folic acid+&quot;, &quot;Folic acid-&quot;),
                                            c(&quot;Total&quot;, &quot;IVF+&quot;, &quot;IVF-&quot;)),
                            dim = c(2, 2, 3)),
                      bias_parms = c(.6, .6, .95, .95))</code></pre>
<pre><code>## --Observed data-- 
##          Outcome: Twins+ 
##        Comparing: Folic acid+ vs. Folic acid- 
## 
## , , Total
## 
##        Folic acid+ Folic acid-
## Twins+        1319        5641
## Twins-       38054      405546
## 
## , , IVF+
## 
##        Folic acid+ Folic acid-
## Twins+         565         781
## Twins-        3583       21958
## 
## , , IVF-
## 
##        Folic acid+ Folic acid-
## Twins+         754        4860
## Twins-       34471      383588
## 
## 
##                                      2.5%    97.5%
## Observed Relative Risk: 2.441910 2.301898 2.590437
##    Observed Odds Ratio: 2.491888 2.344757 2.648251
## ---
##                                                       Observed Corrected
##                       SMR RR adjusted for confounder: 2.261738  1.000235
##    RR due to confounding by misclassified confounder: 1.079661  2.441337
##           Mantel-Haenszel RR adjusted for confounder: 2.228816  1.000187
## MH RR due to confounding by misclassified confounder: 1.095608  2.441452
##                       SMR OR adjusted for confounder: 2.337898  1.000304
##    OR due to confounding by misclassified confounder: 1.065867  2.491131
##           Mantel-Haenszel OR adjusted for confounder: 2.290469  1.000215
## MH OR due to confounding by misclassified confounder: 1.087938  2.491351</code></pre>
<p>While the non-adjusted analysis showed that women taking folic acid were 2.44
times more likely to have twins, after correcting for the misclassification of
IVF, risk ratio is now null (= 1.0).</p>
<p>Second, confidence intervals for corrected association due to exposure
misclassification are now available.
While previously you could already bootstrapped the estimates, you can also now
get the confidence intervals from the variance of the corrected odds ratio
estimator, as in <a href="http://onlinelibrary.wiley.com/doi/10.1002/sim.4780070704/full#abstract">Greenland et
al.</a>
and <a href="http://www.sciencedirect.com/science/article/pii/S1047279706000688">Chu et
al.</a>.
Using the example in Chu et al. of a case-control study of cigarette smoking and
invasive pneumococcal disease, the unadjusted odds ratio is 4.32, with a 95%
confidence interval of 2.96 to 6.31.
Let’s say the sensitivity of self-reported smoking is 94% and specificity is
97%, for both the case and control groups:</p>
<pre class="r"><code>misclassification(matrix(c(126, 92, 71, 224),
                         dimnames = list(c(&quot;Case&quot;, &quot;Control&quot;),
                                         c(&quot;Smoking +&quot;, &quot;Smoking - &quot;)),
                         nrow = 2, byrow = TRUE),
                  type = &quot;exposure&quot;,
                  bias_parms = c(0.94, 0.94, 0.97, 0.97))</code></pre>
<pre><code>## --Observed data-- 
##          Outcome: Case 
##        Comparing: Smoking + vs. Smoking -  
## 
##         Smoking + Smoking - 
## Case          126         92
## Control        71        224
## 
##                                      2.5%    97.5%
## Observed Relative Risk: 2.196866 1.796016 2.687181
##    Observed Odds Ratio: 4.320882 2.958402 6.310846
## ---
##                                                              2.5%    97.5%
## Misclassification Bias Corrected Relative Risk: 2.377254                  
##    Misclassification Bias Corrected Odds Ratio: 5.024508 3.282534 7.690912</code></pre>
<p>The corrected odds ratio is now 5.02, with a widened 95% confidence interval
(3.28 to 7.69).
Note the bias despite the large sensitivity and specificity.</p>
<p>You can even reproduce the contour plots in Chu et al. paper!</p>
<pre class="r"><code>dat &lt;- expand.grid(Se = seq(0.582, 1, 0.02),
                   Sp = seq(0.762, 1, 0.02))

dat$OR_c &lt;- apply(dat, 1,
                  function(x) misclassification(matrix(c(126, 92, 71, 224),
                                                       nrow = 2, byrow = TRUE),
                                                type = &quot;exposure&quot;,
                                                bias_parms = c(x[1], x[1], x[2], x[2]))$adj.measures[2, 1])
dat$OR_c &lt;- round(dat$OR_c, 2)

library(ggplot2)
library(directlabels)
p1 &lt;- ggplot(dat, aes(x = Se, y = Sp, z = OR_c)) +
    geom_contour(aes(colour = ..level..), breaks = c(4.32, 6.96, 8.56, 12.79, 23.41, 432.1)) +
    annotate(&quot;text&quot;, x = 1, y = 1, label = &quot;4.32&quot;, size = 4) +
    scale_fill_gradient(limits = range(dat$OR_c), high = &#39;red&#39;, low = &#39;green&#39;) +
    scale_x_continuous(breaks = seq(0.5, 1, .1), expand = c(0,0)) +
    scale_y_continuous(breaks = seq(0.5, 1, .1), expand = c(0,0)) +
    coord_fixed(ylim = c(0.5, 1.025), xlim = c(0.5, 1.025)) +
    scale_colour_gradient(guide = &#39;none&#39;) +
    theme(plot.title = element_text(face = &quot;bold&quot;, size = 16),
          axis.title = element_text(face=&quot;bold&quot;, size = 14),
          axis.text.y = element_text(colour=&quot;grey42&quot;, size = 12),
          axis.text.x = element_text(colour=&quot;grey42&quot;, size = 12),
          legend.position = &quot;none&quot;) +
    xlab(&quot;Sensitivity&quot;) +
    ylab(&quot;Specificity&quot;) +
    ggtitle(&quot;Estimate of Corrected OR&quot;)
direct.label(p1, list(&quot;far.from.others.borders&quot;, &quot;calc.boxes&quot;, &quot;enlarge.box&quot;, 
                           hjust=1, vjust=-.5, box.color = NA, cex = .9,
                           fill = &quot;transparent&quot;, &quot;draw.rects&quot;))</code></pre>
<div class="figure"><span id="fig:unnamed-chunk-3"></span>
<img src="/blog/2017-08-21-episensr-090_files/figure-html/unnamed-chunk-3-1.png" alt="Contour plot of point estimate of corrected odds ratio (OR)" width="672" />
<p class="caption">
Figure 1: Contour plot of point estimate of corrected odds ratio (OR)
</p>
</div>
<pre class="r"><code>dat$ORc_lci &lt;- apply(dat, 1,
                     function(x) misclassification(matrix(c(126, 92, 71, 224),
                                                          nrow = 2, byrow = TRUE),
                                                   type = &quot;exposure&quot;,
                                                   bias_parms = c(x[1], x[1], x[2], x[2]))$adj.measures[2, 2])
dat$ORc_lci &lt;- round(dat$ORc_lci, 2)

p3 &lt;- ggplot(dat, aes(x = Se, y = Sp, z = ORc_lci)) +
    geom_contour(aes(colour = ..level..),
                 breaks = c(4.05, 4.64, 5.68, 7.00, 9.60)) +
    annotate(&quot;text&quot;, x = 1, y = 1, label = &quot;2.96&quot;, size = 4) +
    scale_fill_gradient(limits = range(dat$ORc_lci), high = &#39;red&#39;, low = &#39;green&#39;) +
    scale_x_continuous(breaks = seq(0.5, 1, .1), expand = c(0,0)) +
    scale_y_continuous(breaks = seq(0.5, 1, .1), expand = c(0,0)) +
    coord_fixed(ylim = c(0.5, 1.025), xlim = c(0.5, 1.025)) +
    scale_colour_gradient(guide = &#39;none&#39;) +
    theme(plot.title = element_text(face = &quot;bold&quot;, size = 16),
          axis.title = element_text(face=&quot;bold&quot;, size = 14),
          axis.text.y = element_text(colour=&quot;grey42&quot;, size = 12),
          axis.text.x = element_text(colour=&quot;grey42&quot;, size = 12),
          legend.position = &quot;none&quot;) +
    xlab(&quot;Sensitivity&quot;) +
    ylab(&quot;Specificity&quot;) +
    ggtitle(&quot;95% LCI of Corrected OR&quot;)
direct.label(p3, list(&quot;far.from.others.borders&quot;, &quot;calc.boxes&quot;, &quot;enlarge.box&quot;, 
                           hjust=1, vjust=-.5, box.color = NA, cex = .9,
                           fill = &quot;transparent&quot;, &quot;draw.rects&quot;))</code></pre>
<div class="figure"><span id="fig:unnamed-chunk-4"></span>
<img src="/blog/2017-08-21-episensr-090_files/figure-html/unnamed-chunk-4-1.png" alt="Contour plot of 95% lower confidence limit of corrected OR" width="672" />
<p class="caption">
Figure 2: Contour plot of 95% lower confidence limit of corrected OR
</p>
</div>
